# Generated by Django 5.2.17 on 2026-10-03 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\S", "Enter a title containing non-whitespace text."
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("topic", models.CharField(blank=True, default="", max_length=100)),
                ("starts_at", models.DateTimeField()),
                ("speaker", models.CharField(blank=True, default="", max_length=255)),
                ("is_example", models.BooleanField(default=False)),
                (
                    "seed_key",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True, unique=True
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("title__regex", "\\S")),
                        name="event_title_has_text",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("seed_key__isnull", True),
                            ("seed_key__regex", "\\S"),
                            _connector="OR",
                        ),
                        name="event_seed_key_null_or_text",
                    ),
                ],
            },
        ),
    ]
