# Generated by Django 5.2.17 on 2026-10-03 23:33

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=500,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\S", "Enter a title containing non-whitespace text."
                            )
                        ],
                    ),
                ),
                ("authors", models.TextField(blank=True, default="")),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                    ),
                ),
                (
                    "original_url",
                    models.URLField(
                        max_length=2048,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=2048,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("research_paper", "Research paper"),
                            ("article", "Article / web resource"),
                        ],
                        default="article",
                        max_length=20,
                    ),
                ),
                (
                    "metadata_source",
                    models.CharField(
                        choices=[("crossref", "Crossref"), ("manual", "Manual")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "seed_key",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True, unique=True
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("title__regex", "\\S")),
                        name="resource_title_has_text",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("year__isnull", True),
                            models.Q(("year__gte", 1), ("year__lte", 9999)),
                            _connector="OR",
                        ),
                        name="resource_year_in_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("original_url__iregex", "^https?://[^[:space:]]+$")
                        ),
                        name="resource_url_http_scheme",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("doi__isnull", True),
                            models.Q(
                                ("doi__regex", "^10\\.[0-9]{4,9}/[^[:space:]]+$"),
                                ("doi", django.db.models.functions.text.Lower("doi")),
                            ),
                            _connector="OR",
                        ),
                        name="resource_doi_canonical_or_null",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("resource_type__in", ["research_paper", "article"])
                        ),
                        name="resource_type_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("metadata_source__in", ["crossref", "manual"])
                        ),
                        name="resource_source_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("seed_key__isnull", True),
                            ("seed_key__regex", "\\S"),
                            _connector="OR",
                        ),
                        name="resource_seed_null_or_text",
                    ),
                ],
            },
        ),
    ]
