# Generated by Django 5.2.17 on 2026-10-04 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_resource"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommendation", models.TextField(blank=True, default="")),
                ("display_order", models.IntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_resources",
                        to="events.event",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_resources",
                        to="events.resource",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "resource"), name="unique_event_resource"
                    )
                ],
            },
        ),
    ]
