# Generated by Django 5.2.17 on 2026-10-07 09:34

import events.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_image_alt',
            field=models.CharField(blank=True, default='', help_text='Describe meaningful image content for screen readers; leave empty for decorative artwork. Keep essential event information in the title and description too.', max_length=255, verbose_name='Promotional image description'),
        ),
        migrations.AddField(
            model_name='event',
            name='cover_image_url',
            field=models.CharField(blank=True, default='', help_text='Paste an HTTPS image address, or a bundled /static/events/posters/name.svg path. Leave empty for the default artwork.', max_length=2048, validators=[events.validators.validate_cover_image_url], verbose_name='Promotional image URL'),
        ),
    ]
